name: myapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  cached_network_image: ^3.3.1 # Ensure cached_network_image is in pubspec.yaml
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.8
  flutter_cache_manager: ^3.4.1
  shared_preferences: ^2.2.2
  wallpaper_manager_plus: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true